# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xlW3iMzJoHqaAAMxHWwcJF3rlU7D6ZkC
"""

import requests
import json

#Assign URL to Variable
pokemon_url = "https://pokeapi.co/api/v2/pokemon/1/"
pokemon_form_url = "https://pokeapi.co/api/v2/pokemon-form/1/"

#Set get requests to variable
pokemon_response = requests.get(pokemon_url)
pokemon_form_response = requests.get(pokemon_form_url)

# Check if the request is successful
if pokemon_response.status_code == 200 and pokemon_form_response.status_code == 200:
    #Assign json file to variable
    pokemon_data = pokemon_response.json()
    pokemon_form_data = pokemon_form_response.json()

    #Loop append through stat list
    stats = []
    for stat in pokemon_data['stats']:
        stats.append({
            "base_stat": stat['base_stat'],
            "effort": stat['effort'],
            "stat": {
                "name": stat['stat']['name'],
                "url": stat['stat']['url']
            }
        })

    #Assign name and sprites from pokemon-form/1/ to variable
    name = pokemon_form_data['name']
    sprites = pokemon_form_data['sprites']

    #Group data into json format
    combined_data = {
        "stats": stats,
        "name": name,
        "prites": sprites
    }

    # Convert the combined data to JSON format
    combined_json = json.dumps(combined_data, indent=4)

    post_url = "https://example.com/api"
    headers = {"Content-Type": "application/json"}

    #post
    post_response = requests.post(post_url, data=combined_json, headers=headers)

    if post_response.status_code == 200:
        print("Data successfully sent!")
    else:
        print(f"Failed to send data. Status code: {post_response.status_code}")

    #print json
    print(combined_json)

else:
    print("Failed to retrieve data from the API.")

