# -*- coding: utf-8 -*-
"""CreateWebhook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBMDVgd-ZYpkhmfxUTg8GJtf9SqzufVI
"""

!wget -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
!unzip -o ngrok.zip

!./ngrok http --authtoken YOUR_NGROK_AUTH_TOKEN 5000 &

import time
time.sleep(5)  # Give ngrok time to initialize
!curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

"""Copy the ngrok URL output from the last command, add /callback to it, and set it in the LINE Developer Console as your webhook URL"""