# -*- coding: utf-8 -*-
"""Star.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgRsB9I3WxHXKfjbke5plyJadQzHVrLU
"""

num=int(input())

i=1
while i < num:
  print("*"*i)
  i+=1
while i >= 1:
  print("*"*i)
  i-=1

